#!/usr/bin/env bash
# =============================================================================
#  GLADE one-click setup for macOS (Apple Silicon & Intel)
#
#  Mirrors bootstrap_linux.sh, but:
#    - installs CFITSIO / FFTW / GSL via Homebrew instead of building them from
#      source (much faster, and brew keeps them updated);
#    - builds glafic + its Python extension with the macOS-native linker recipe
#      (`-bundle -undefined dynamic_lookup`, no libpython link, no OpenMP);
#    - generates macOS env.sh / run_glade.sh / run_webui.sh launchers.
#
#  It does NOT touch any Linux file or the committed glafic2/Makefile beyond
#  backing it up to Makefile.original (same as the Linux script).
# =============================================================================
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info() { echo -e "${GREEN}[INFO]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ERR ]${NC} $*"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

GLAFIC_SRC_DIR="${SCRIPT_DIR}/glafic2"
VENV_DIR="${SCRIPT_DIR}/.venv"

# Homebrew packages that provide glafic's C dependencies.
BREW_PACKAGES=(pkg-config gsl cfitsio fftw)

USE_VENV=1   # 1 = virtual environment (default), 0 = global/system Python

# ── 0. install mode ──────────────────────────────────────────────────────────
choose_install_mode() {
  echo
  echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
  echo    "  GLADE Installation Mode / 安装模式选择 (macOS)"
  echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
  echo    "  [1] Virtual environment  — isolated in .venv/ (recommended)"
  echo    "      隔离在 .venv/ 中，不影响系统 Python"
  echo    "  [2] Global / System Python"
  echo    "      直接安装到当前 python3"
  echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
  read -rp "  Choose [1/2] (default: 1): " _choice
  case "${_choice}" in
    2) USE_VENV=0; info "Mode: global system Python install." ;;
    *) USE_VENV=1; info "Mode: virtual environment (.venv/)." ;;
  esac
  echo
}

# ── 1. preflight: Xcode CLT + Homebrew ───────────────────────────────────────
check_toolchain() {
  if ! xcode-select -p >/dev/null 2>&1; then
    err "未检测到 Xcode Command Line Tools（提供 cc / make）。"
    err "请先运行：  xcode-select --install   然后重新执行本脚本。"
    exit 1
  fi
  if ! command -v make >/dev/null 2>&1 || ! command -v cc >/dev/null 2>&1; then
    err "缺少 make 或 cc，请确认 Xcode Command Line Tools 已安装。"
    exit 1
  fi
  if ! command -v brew >/dev/null 2>&1; then
    err "未检测到 Homebrew。请先安装 Homebrew，再重新运行本脚本："
    err '  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
    exit 1
  fi
  BREW_PREFIX="$(brew --prefix)"           # /opt/homebrew (arm64) or /usr/local (Intel)
  info "Homebrew prefix: ${BREW_PREFIX}"
}

install_brew_packages() {
  info "通过 Homebrew 安装系统依赖：${BREW_PACKAGES[*]}"
  # `brew install` is idempotent; already-installed formulae are skipped.
  brew install "${BREW_PACKAGES[@]}"
  # Ensure headers/libs are linked into the main prefix (gsl/cfitsio/fftw are
  # keg-only on some setups; force the symlinks so -I/-L on the prefix resolve).
  for f in "${BREW_PACKAGES[@]}"; do
    brew link --overwrite "${f}" >/dev/null 2>&1 || true
  done
}

# ── 2. macOS Makefile for glafic ─────────────────────────────────────────────
write_glafic_makefile() {
  cd "${GLAFIC_SRC_DIR}"
  if [[ -f Makefile && ! -f Makefile.original ]]; then
    cp Makefile Makefile.original
    info "原 Makefile 已备份为 Makefile.original"
  fi
  cat > Makefile <<EOF
# Auto-generated by bootstrap_macos.sh — do not edit by hand.
# Restore the upstream Makefile from Makefile.original if needed.
UNAME_S := \$(shell uname -s)
UNAME_M := \$(shell uname -m)

BREW_PREFIX = ${BREW_PREFIX}
LIBPATH = \$(BREW_PREFIX)/lib
INCPATH = \$(BREW_PREFIX)/include

CC      = cc
CFLAGS  = -O2 -Wall -fPIC -I\$(INCPATH)
# Brew dylibs carry absolute install_names, so no DYLD path is needed at runtime;
# -rpath is added defensively. No OpenMP (glafic does not use it).
LIBS    = -lm -L\$(LIBPATH) -lcfitsio -lfftw3 -lgsl -lgslcblas -lcurl -lz -Wl,-rpath,\$(LIBPATH)

BIN     = glafic
OBJ_BIN = glafic.o
OBJS    = call.o ein_tab.o mass.o util.o fits.o \\
	  init.o distance.o gsl_zbrent.o gsl_integration.o \\
	  source.o extend.o point.o opt_extend.o opt_lens.o \\
	  opt_point.o example.o mock.o calcein.o vary.o \\
	  gnfw_tab.o commands.o mcmc.o amoeba_opt.o app_ell.o \\
	  app_cnfw.o

LIB     = libglafic.a
AR      = ar
AFLAGS  = r

# Python extension: the canonical macOS recipe for a CPython extension module is
# a bundle with dynamic_lookup (symbols resolved from the host interpreter at
# import time). We deliberately do NOT link libpython / use --embed here.
PY      = python/glafic/glafic.so
OBJ_PY  = python.o
CFLAGS3 = -Wall -bundle -undefined dynamic_lookup -L\$(LIBPATH) -Wl,-rpath,\$(LIBPATH)
PY_INC := \$(shell python3-config --includes)
PY_LIBS = -lm -L\$(LIBPATH) -lcfitsio -lfftw3 -lgsl -lgslcblas -lcurl -lz

default: all
all: bin lib python

bin: \$(OBJ_BIN) \$(OBJS)
	\$(CC) \$(CFLAGS) -o \$(BIN) \$(OBJ_BIN) \$(OBJS) \$(LIBS)

lib: \$(OBJS)
	\$(AR) \$(AFLAGS) \$(LIB) \$(OBJS)

python: \$(OBJ_PY) \$(OBJS)
	\$(CC) \$(CFLAGS3) -o \$(PY) \$(OBJ_PY) \$(OBJS) \$(PY_LIBS)

python.o:python.c glafic.h
	\$(CC) \$(CFLAGS) \$(PY_INC) -c \$< -o \$@

%.o:%.c glafic.h
	\$(CC) \$(CFLAGS) -c \$< -o \$@

clean:
	-rm -f \$(BIN) \$(OBJ_BIN) \$(OBJS) \$(LIB) \$(PY) \$(OBJ_PY) *~ \\#* core*
EOF
  cd "${SCRIPT_DIR}"
}

build_glafic() {
  if [[ ! -d "${GLAFIC_SRC_DIR}" ]]; then
    err "未找到 glafic2 源码目录：${GLAFIC_SRC_DIR}"
    exit 1
  fi
  write_glafic_makefile
  cd "${GLAFIC_SRC_DIR}"
  info "编译 glafic2（二进制 + Python 模块）..."
  make clean || true
  make -j"$(sysctl -n hw.logicalcpu)" all
  if [[ ! -f "${GLAFIC_SRC_DIR}/glafic" ]]; then
    err "glafic 可执行文件编译失败。"; exit 1
  fi
  if [[ ! -f "${GLAFIC_SRC_DIR}/python/glafic/glafic.so" ]]; then
    err "glafic Python 模块编译失败。"; exit 1
  fi
  info "glafic 编译完成。"
  cd "${SCRIPT_DIR}"
}

# ── 3. Python env ────────────────────────────────────────────────────────────
setup_python_env() {
  if [[ "${USE_VENV}" -eq 1 ]]; then
    info "创建 Python 虚拟环境 (.venv/)..."
    python3 -m venv "${VENV_DIR}"
    # shellcheck disable=SC1091
    source "${VENV_DIR}/bin/activate"
    pip install --upgrade pip setuptools wheel
    pip install -r "${SCRIPT_DIR}/requirements.txt"
  else
    info "全局安装 Python 依赖 (system Python)..."
    local bsp_flag=""
    if pip3 install --help 2>&1 | grep -q -- "--break-system-packages"; then
      bsp_flag="--break-system-packages"
    fi
    # shellcheck disable=SC2086
    pip3 install ${bsp_flag} --upgrade pip setuptools wheel
    # shellcheck disable=SC2086
    pip3 install ${bsp_flag} --ignore-installed -r "${SCRIPT_DIR}/requirements.txt"
  fi
}

install_glafic_to_python() {
  local glafic_py_dir="${GLAFIC_SRC_DIR}/python"
  local pth_name="glafic_glade.pth"
  local site_pkgs
  if [[ "${USE_VENV}" -eq 1 ]]; then
    site_pkgs="$("${VENV_DIR}/bin/python3" -c "import site; print(site.getsitepackages()[0])")"
  else
    site_pkgs="$(python3 -c "import site; print(site.getsitepackages()[0])")"
  fi
  info "注册 glafic 模块路径到 site-packages..."
  echo "${glafic_py_dir}" > "${site_pkgs}/${pth_name}"
  info "  ${glafic_py_dir} -> ${site_pkgs}/${pth_name}"
}

# ── 4. launchers (env.sh / run_glade.sh / run_webui.sh) ──────────────────────
write_env_script() {
  {
    cat <<'ENVEOF'
#!/usr/bin/env bash
set -e
GLADE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GLAFIC_HOME="${GLADE_ROOT}/glafic2"
GLAFIC_PYTHON_PATH="${GLAFIC_HOME}/python"
ENVEOF
    echo "GLAFIC_LIB_PATH=\"${BREW_PREFIX}/lib\""
    if [[ "${USE_VENV}" -eq 1 ]]; then
      cat <<'VENVEOF'

if [[ -f "${GLADE_ROOT}/.venv/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source "${GLADE_ROOT}/.venv/bin/activate"
fi
VENVEOF
    fi
    cat <<'ENVEOF'

export GLADE_ROOT
export GLAFIC_HOME
export GLAFIC_PYTHON_PATH
export GLAFIC_LIB_PATH
export PYTHONPATH="${GLADE_ROOT}:${GLAFIC_PYTHON_PATH}:${GLADE_ROOT}/Rhongomyniad:${GLADE_ROOT}/tools:${PYTHONPATH:-}"
# macOS resolves brew dylibs by absolute install_name; this fallback is defensive.
export DYLD_FALLBACK_LIBRARY_PATH="${GLAFIC_LIB_PATH}:${DYLD_FALLBACK_LIBRARY_PATH:-/usr/local/lib:/usr/lib}"
export PATH="${GLAFIC_HOME}:${PATH}"
ENVEOF
  } > "${SCRIPT_DIR}/env.sh"
  chmod +x "${SCRIPT_DIR}/env.sh"
}

write_run_script() {
  cat > "${SCRIPT_DIR}/run_glade.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/env.sh"
python3 "${SCRIPT_DIR}/main.py" "$@"
EOF
  chmod +x "${SCRIPT_DIR}/run_glade.sh"
}

write_webui_script() {
  cat > "${SCRIPT_DIR}/run_webui.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/env.sh"
GLADE_PORT="${GLADE_PORT:-6017}"
export GLADE_PORT
echo "============================================================"
echo "  GLADE WebUI"
echo "  Open in browser: http://localhost:${GLADE_PORT}"
echo "  Press Ctrl+C to stop"
echo "============================================================"
python3 "${SCRIPT_DIR}/webui/app.py"
EOF
  chmod +x "${SCRIPT_DIR}/run_webui.sh"
}

# ── 5. verify ────────────────────────────────────────────────────────────────
verify_installation() {
  local python_bin
  if [[ "${USE_VENV}" -eq 1 ]]; then
    python_bin="${VENV_DIR}/bin/python3"
  else
    python_bin="python3"
  fi
  info "验证 glafic Python 模块导入..."
  "${python_bin}" - <<'PY'
import sys
try:
    import glafic
    print("  [OK] import glafic  ->", glafic.__file__)
except Exception as e:  # noqa: BLE001
    print("  [FAIL]", e); sys.exit(1)
PY
  info "验证多进程 start method（macOS 应为 spawn）..."
  "${python_bin}" - <<'PY'
from core.parallel import preferred_start_method
print("  preferred_start_method() =", preferred_start_method())
PY
  info "全部验证通过。"
}

# ── main ─────────────────────────────────────────────────────────────────────
do_install() {
  info "开始为 macOS 自动搭建 GLADE 环境..."
  choose_install_mode
  check_toolchain
  install_brew_packages
  build_glafic
  setup_python_env
  install_glafic_to_python
  write_env_script
  write_run_script
  write_webui_script
  verify_installation

  echo
  echo "================================================================"
  info "全部完成 (macOS / ${BREW_PREFIX})。"
  if [[ "${USE_VENV}" -eq 1 ]]; then
    echo "  安装模式: 虚拟环境 (.venv/)"
  else
    echo "  安装模式: 全局 system Python"
  fi
  echo "================================================================"
  echo
  echo "下一步:"
  echo "  WebUI:    ./run_webui.sh      然后浏览器打开 http://localhost:6017"
  echo "  命令行:    ./run_glade.sh"
  echo "  手动环境:  source env.sh"
  echo
  echo "并行说明: DE / MCMC 在 macOS 上自动使用 spawn 进程池（结果与 Linux 一致）。"
  echo "          多进程数量沿用 DE_WORKERS / MCMC_WORKERS（-1 = 全核）。"
}

do_install "$@"
